dice-cyfronet/atmosphere

Gemfile.lock, app/abilities/atmosphere/appliance_ability_builder.rb, app/controllers/atmosphere/api/v1/appliances_controller.rb, app/providers/atmosphere/optimization_strategy/default.rb, app/providers/atmosphere/optimization_strategy/manual.rb, app/services/atmosphere/appliance_vms_manager.rb, app/services/atmosphere/billing_service.rb, app/services/atmosphere/optimizer.rb, spec/providers/atmosphere/optimization_strategy/manual_spec.rb, spec/requests/atmosphere/api/appliances_spec.rb, spec/services/atmosphere/appliance_vms_manager_spec.rb, spec/services/atmosphere/optimizer_spec.rb
=> Scaling - initial draft 

README.md
new step (nr 6) added to contributing section
=> add contributing ready for review step

app/models/atmosphere/virtual_machine_template.rb
It seems like private `save_template_in_cloud` method is not used - removing.
=> remove unused private method

app/controllers/atmosphere/api/application_controller.rb, app/controllers/atmosphere/api/v1/appliance_configuration_templates_controller.rb, app/controllers/atmosphere/api/v1/appliance_sets_controller.rb, app/controllers/atmosphere/api/v1/appliance_types_controller.rb, app/controllers/atmosphere/api/v1/appliances_controller.rb, app/controllers/atmosphere/api/v1/dev_mode_property_sets_controller.rb, app/controllers/atmosphere/api/v1/endpoints_controller.rb, app/controllers/atmosphere/api/v1/http_mappings_controller.rb, app/controllers/atmosphere/api/v1/port_mapping_properties_controller.rb, app/controllers/atmosphere/api/v1/port_mapping_templates_controller.rb, app/controllers/atmosphere/api/v1/user_keys_controller.rb, app/controllers/concerns/atmosphere/api/auditable.rb, config/locales/user_actions.yml
We are repeating all over again the same schema for logging user actions. Auditable concern is trying to encapsulate this feature in one place.
/cc @Nuanda, @nowakowski please take a look
=> auditable concern for user actions

app/serializers/atmosphere/user_serializer.rb, doc/api/users.md, spec/requests/atmosphere/api/users_spec.rb, spec/serializers/atmosphere/user_serializer_spec.rb
Fixes #76 
/cc @dice-cyfronet/atmo-dev-team, @dharezlak please take a look
=> user details for current_user

atmosphere.gemspec
/cc @dice-cyfronet/atmo-dev-team
=> Set correct atmosphere homepage url

app/views/atmosphere/admin/compute_sites/index.html.haml, app/views/atmosphere/admin/funds/index.html.haml, app/views/atmosphere/admin/user_keys/index.html.haml
=> Move buttons to right top corner

app/views/atmosphere/admin/compute_sites/index.html.haml, config/locales/en.yml
@mkasztelnik @paoolo Please review.
Fixes #90
=> Added a more verbose warning message when deleting CS via the admin GUI.

app/assets/stylesheets/atmosphere/application.scss, app/assets/stylesheets/atmosphere/sections/funds.scss, app/controllers/atmosphere/admin/user_funds_controller.rb, app/models/atmosphere/user_fund.rb, app/views/atmosphere/admin/funds/_user_fund.html.haml, app/views/atmosphere/admin/funds/index.html.haml, config/locales/en.yml, config/routes.rb, spec/models/atmosphere/user_fund_spec.rb, spec/services/atmosphere/billing_service_spec.rb
=> Ensure default fund

app/services/atmosphere/dnat_wrangler.rb, spec/services/atmosphere/dnat_wrangler_spec.rb
Necessary changes required when dice-cyfronet/ip-wrangler#7 PR will be merged and deployed.
Introduced changes are backward compatible.
=> 200 and 204 as success while deleting dnat redirection

.hound.yml, .rubocop.yml
=> Disable `schema.db` from Hound review

README.md
=> atmosphere gem name corrected

lib/atmosphere/engine.rb
=> exposing factories only in test

app/abilities/atmosphere/appliance_ability_builder.rb, app/abilities/atmosphere/appliance_ability_builder_ext.rb, app/controllers/atmosphere/api/v1/appliance_sets_controller.rb, app/controllers/concerns/atmosphere/api/v1/appliance_sets_controller_ext.rb, app/models/atmosphere/appliance.rb, app/models/atmosphere/appliance_set.rb, app/models/concerns/atmosphere/appliance_ext.rb, app/models/concerns/atmosphere/appliance_set_ext.rb, app/serializers/atmosphere/appliance_serializer.rb, app/serializers/atmosphere/appliance_serializer_ext.rb, app/serializers/atmosphere/appliance_set_serializer.rb, app/serializers/atmosphere/appliance_set_serializer_ext.rb, app/serializers/atmosphere/user_serializer.rb, app/serializers/atmosphere/user_serializer_ext.rb, app/services/atmosphere/appliance_creator.rb, app/services/atmosphere/appliance_creator_ext.rb
It is required to implement support for user team in the scope of plgrid project.
=> Extensions for setting additional params while creating appliance set and appliance

app/models/atmosphere/virtual_machine.rb
`acition_name` => `action_name`
Fix #89 
=> Correct parameter name

app/models/atmosphere/appliance_set.rb
Fix #53
@dice-cyfronet/atmo-dev-team, especially @bwilk please take a look at it.
=> Improve clew appliances query

app/views/atmosphere/admin/appliance_types/_view.html.haml, config/locales/en.yml
=> Add more meaningful warning while deleting AT

Gemfile.lock, app/controllers/atmosphere/api/v1/appliance_types_controller.rb, app/models/atmosphere/compute_site.rb, app/services/atmosphere/cloud/vm_creator.rb, app/services/atmosphere/flavor_manager.rb, app/services/atmosphere/save_as_service.rb, app/services/atmosphere/vm_updater.rb, app/workers/atmosphere/vm_tags_creator_worker.rb, app/workers/atmosphere/vm_template_monitoring_worker.rb, atmosphere.gemspec, config/initializers/unify_google_compute.rb
=> Possibility to create Google compute client

app/controllers/atmosphere/api/v1/appliance_types_controller.rb, config/locales/en.yml
=> Externalize and improve AT controller messages

config/initializers/unify_google_compute.rb
Snapshot is used to save VM as VMT. Snapshots on google compute can be created without destroying instances. Additionally snapshots are a little bit cheaper than images.
=> Save at google compute

app/models/atmosphere/flavor_os_family.rb, db/migrate/20150113100404_add_osfamilies.rb
=> Fixes incorrect assignment of OS families to VM flavors in schema migration

.travis.yml, app/controllers/atmosphere/admin/appliance_types_controller.rb, app/controllers/atmosphere/api/v1/appliance_types_controller.rb, app/models/atmosphere/appliance_type.rb, app/views/atmosphere/admin/appliance_types/_edit.html.haml, app/views/atmosphere/admin/appliance_types/_view.html.haml, app/views/atmosphere/admin/appliance_types/edit.html.haml, app/views/atmosphere/admin/appliance_types/index.html.haml, app/views/atmosphere/admin/appliance_types/new.html.haml, app/views/atmosphere/admin/appliance_types/show.html.haml, db/migrate/20150113100404_add_osfamilies.rb, spec/dummy/db/seeds.rb, spec/factories/appliance_types.rb, spec/models/atmosphere/appliance_type_spec.rb, spec/providers/atmosphere/optimization_strategy/default_spec.rb, spec/requests/atmosphere/api/appliance_types_spec.rb
=> At os family setup

app/models/atmosphere/appliance.rb, spec/models/atmosphere/appliance_spec.rb
=> appliance chooses its funding more sensibly now

app/models/atmosphere/compute_site.rb, app/providers/atmosphere/optimization_strategy/default.rb, spec/models/atmosphere/compute_site_spec.rb, spec/providers/atmosphere/optimization_strategy/default_spec.rb, spec/providers/atmosphere/optimization_strategy/manual_spec.rb, spec/services/atmosphere/optimizer_spec.rb
=> Optimizer considers only funded cs

Gemfile.lock, app/services/atmosphere/cloud/destroy_unused_vms.rb, app/services/atmosphere/optimizer.rb, config/locales/en.yml, spec/services/atmosphere/cloud/destroy_unused_vms_spec.rb
The goal is to extract all logic from `Atmosphere::Optimizer`. This is first step.
=> Extract destroy unused VMs into service

app/views/atmosphere/admin/virtual_machine_templates/show.html.haml
=> fixed wrong path in VMT show view

app/controllers/atmosphere/admin/virtual_machine_flavors_controller.rb, app/helpers/atmosphere/virtual_machine_flavors_helper.rb, app/models/atmosphere/flavor_os_family.rb, app/models/atmosphere/virtual_machine_flavor.rb, app/views/atmosphere/admin/compute_sites/index.html.haml, app/views/atmosphere/admin/virtual_machine_flavors/_form.html.haml, app/views/atmosphere/admin/virtual_machine_flavors/edit.html.haml, config/locales/en.yml, config/routes.rb, spec/models/atmosphere/flavor_os_family_spec.rb, spec/models/atmosphere/virtual_machine_flavor_spec.rb
=> Flavor cost management ui

app/models/atmosphere/virtual_machine.rb, spec/models/atmosphere/virtual_machine_spec.rb, spec/models/atmosphere/virtual_machine_template_spec.rb
=> vm.destroy callback stops operation when called on unmanaged vm

app/views/atmosphere/admin/appliance_sets/_appliance_details.html.haml, app/views/atmosphere/admin/appliance_sets/index.html.haml
Needed for https://gitlab.dev.cyfronet.pl/atmosphere/plgrid/merge_requests/28
=> Used by PLGrid deployment to show extended appliance info

app/controllers/atmosphere/api/v1/clew_controller.rb, spec/requests/atmosphere/api/clew_spec.rb
=> Load admin abilities only when user asks for it

app/models/atmosphere/appliance.rb, spec/models/atmosphere/appliance_spec.rb
Updates appliance fund selection logic to acknowledge the contents of appliance.tenants and also the list of funds available to the appliance's owner.
=> Fix fund selection for appliance.

app/models/atmosphere/user_key.rb
=> Remove user keys only from active tenants

app/abilities/atmosphere/port_mapping_property_ability_builder.rb, app/models/atmosphere/dev_mode_property_set.rb, app/providers/atmosphere/default_pdp.rb, spec/abilities/atmosphere/port_mapping_property_ability_builder_spec.rb, spec/models/atmosphere/dev_mode_property_set_spec.rb, spec/providers/atmosphere/default_pdp_spec.rb
=> Manage pmt prop in dev mode

app/controllers/atmosphere/admin/user_keys_controller.rb, app/views/atmosphere/admin/user_keys/_form.html.haml
Use simple form association for selecting user key owner
Fix #164
=> Fix user key form

app/controllers/atmosphere/admin/virtual_machines_controller.rb
Fix #229 in stable branch. e465176805d6ecb58c761bd17c9b41d5fefeeaf9 should be also cherry-picked into master branch
=> Fix save action on admin VM view

app/models/atmosphere/virtual_machine.rb, spec/models/atmosphere/virtual_machine_spec.rb
=> Allow delete non managed VM from Atmosphere DB

app/controllers/atmosphere/api/application_controller.rb
=> Handle billing exception

app/models/atmosphere/fund.rb
Fix #223
@dice-cyfronet/atmo-dev-team, @mpawlik please take a look
=> Add validation for max fund balance value

doc/api/README.md
=> Describe generic JSON structure and JSON request content type

doc/api/README.md
=> Remove mi_ticket from API documentation

app/models/atmosphere/appliance.rb, app/providers/atmosphere/optimization_strategy/default.rb, app/providers/atmosphere/optimization_strategy/manual.rb, spec/models/atmosphere/appliance_spec.rb, spec/providers/atmosphere/optimization_strategy/default_spec.rb, spec/providers/atmosphere/optimization_strategy/manual_spec.rb
https://github.com/dice-cyfronet/atmosphere/issues/245
=> check if strategies support appl set of given type

.rubocop.yml, Gemfile, Gemfile.lock, app/models/atmosphere/appliance.rb, app/providers/atmosphere/optimization_strategy/default.rb, app/services/atmosphere/cloud/satisfy_appliance.rb, spec/factories/appliances.rb, spec/models/atmosphere/appliance_spec.rb, spec/services/atmosphere/cloud/satisfy_appliance_spec.rb, spec/services/atmosphere/optimizer_spec.rb
=> Updated fund assignment logic

app/controllers/atmosphere/api/v1/virtual_machine_flavors_controller.rb
This solves point 3.12 from security audit
=> Improved number validation regexp

app/models/atmosphere/tenant.rb
This solves point 3.16 from security audit.
=> Remove unused (unsafe for sql injection) code

app/models/atmosphere/user_key.rb, spec/models/atmosphere/user_key_spec.rb
Fix https://github.com/dice-cyfronet/atmosphere/issues/259
=> sanitize public key content

app/controllers/atmosphere/api/v1/appliances_controller.rb, doc/api/appliances.md, spec/requests/atmosphere/api/appliances_spec.rb
see https://jira.plgrid.pl/jira/browse/PLGCZ-40
=> Stop action in appliance REST API

app/models/atmosphere/virtual_machine_template.rb, app/providers/atmosphere/optimization_strategy/default.rb
Solves a serious performance bottleneck in PL-Grid GUI. Urgent.
=> Fix n+1 query problem in optimizer
