spec/requests/atmosphere/api/appliance_configuration_templates_spec.rb
in 
```ruby
it 'returns 403 Forbidden when creating configuration template for not owned appliance type' do
post api("/appliance_configuration_templates", user), new_not_owned_config_template_request
end
```
following line was missing
```ruby
expect(response.status).to eq 403
```
/cc @dice-cyfronet/atmo-dev please take a look
=> add missing asert for forbidden post action

app/serializers/atmosphere/appliance_set_serializer.rb, doc/api/appliance_sets.md, spec/serializers/atmosphere/appliance_set_serializer_spec.rb
As @dharezlak noticed `optimization_policy` was not returned by REST API. This PR adds missing field.
/cc @dice-cyfronet/atmo-dev please take a look
=> optimization_policy in appliance set serializer

app/models/atmosphere/virtual_machine.rb, app/models/atmosphere/virtual_machine_template.rb, spec/models/atmosphere/virtual_machine_spec.rb, spec/models/atmosphere/virtual_machine_template_spec.rb
We should not care about VM, VMT not found exception thrown by compute site when destroying `Atmosphere::VirtualMachine`, `Atmosphere::VirtualMachineTemplate`.
Fixes #50
=> ignore destroy on cloud not found exception

lib/atmosphere.rb, lib/atmosphere/clockwork.rb, lib/generators/templates/atmosphere.rb
Rationale: ismop experiment, when we need to determine quite fast when VMs are up and running.
=> vm and vmt monitoring intervals from config

atmosphere.gemspec, lib/atmosphere/engine.rb
I need to use factories from Atmo specs in PLGrid application. This fix is done according to this solution:
http://stackoverflow.com/questions/20261585/how-to-use-factorygirl-factories-from-an-engine
=> allow apps to use this engine's factories in rspecs

app/services/atmosphere/vm_updater.rb, spec/services/atmosphere/vm_updater_spec.rb
Childhood age is used to fix the problem when following situation occurs:
- atmosphere send request to start VM
- after request is sent monitoring is triggered, new VM is discovered and registered as `managed_by_atmosphere = false`
- atmosphere is trying to save VM created in first step into DB. As a result  exception is thrown (VM with id_at_site already exists)
We used `server.created` from compute site to fix this problem. It has one drawback - when compute site host data is different that date on the host where atmosphere is hosted. To minimize this problem this commit introduces checking at the beginning `created_at` field and only when it is empty `created` date returned by the compute site is used.
/cc @dice-cyfronet/atmo-dev-team please take a look.
=> take into account created at when checking vm age

app/controllers/atmosphere/api/v1/appliance_types_controller.rb, app/controllers/concerns/atmosphere/api/v1/appliance_types_controller_ext.rb
Changes required to fix [this spec](https://github.com/VPH-Share/atmosphere-vph/blob/master/spec/requests/atmosphere/appliance_types_spec.rb) in vph deployment.
=> appliance types allowed params customization

app/exceptions/atmosphere/unsuported_exception.rb, app/exceptions/atmosphere/unsupported_exception.rb, config/initializers/unify_fog_cloud_clients.rb
Before we started using Rails engine we had an exception Air::UnsuportedOperation. Please notice the typo in exception class name. After we switched to engine the module of this exception was renamed to Atmosphere, however the code that raises this exception was not refactored accordingly. This PR fixes this bug.
=> Correct exception name

app/models/atmosphere/virtual_machine_template.rb, app/services/atmosphere/cloud/vmt_updater.rb, spec/models/atmosphere/virtual_machine_template_spec.rb, spec/services/atmosphere/cloud/vmt_updater_spec.rb
It solved the problem when VMT is migrated into Amazon. There it is not possible to register template and set its metadata as atomic operation. As a conclusion VMT was first discovered but not assigned to appliance type and version was not set. Next after metadata was added monitoring assigns this VMT into appliance type and set version into `appliance_type.version + 1`. This is obviously bug. This commit fixes this issue, by allowing to update version by the monitoring when VMT is young. What is more during "young" period if administrator changes source VMT version it will be populated into migrated VMT.
Fixes #112 and #113
=> setting version has precedence over setting AT

app/models/atmosphere/compute_site.rb, app/models/atmosphere/user_key.rb, app/services/atmosphere/vm_updater.rb, app/workers/atmosphere/vm_tags_creator_worker.rb, config/initializers/unify_rackspace.rb
In the scope of this PR rackspace compute site integration will be implemented. To make it possible following actions need to be supported:
=> Rackspace integration

app/controllers/atmosphere/api/application_controller.rb, app/controllers/concerns/atmosphere/api/application_controller_ext.rb, spec/requests/atmosphere/api/use_session_when_no_api_token_spec.rb
It is useful when Clew is embedded into Atmosphere home page. Than we don't need to pass any token only session cookie and valid CSRF token is needed.
CSRF token can be passed into Clew using following method `form_authenticity_token`.
To distinguish when token authentication should be used dedicated method is created in `Atmosphere::Api::ApplicationControllerExt` `token_request?`. It should return `true` when token is present in the request. It need to be overridden in every project with token support which uses Atmosphere.
=> Use session and CSRF protection when no API token given

app/models/atmosphere/appliance.rb, app/models/atmosphere/appliance_type.rb, app/models/atmosphere/dev_mode_property_set.rb, app/models/atmosphere/os_family.rb, db/migrate/20150224171920_add_osfamily_to_dev_mode_property_sets.rb, spec/dummy/db/schema.rb
Bugfix - enables os_family assignments to be persistently retained when creating new ApplianceTypes
=> Billing in deployments

app/models/atmosphere/appliance_type.rb, db/migrate/20150113100404_add_osfamilies.rb, spec/dummy/db/schema.rb
https://github.com/dice-cyfronet/atmosphere/issues/120
It used to be atomsphere_os_famielies_id and the correct name os_family_id
=> renamed column name in appliance_types table

app/controllers/atmosphere/admin/virtual_machine_templates_controller.rb
Since we moved Atmosphere into engine
```ruby
Rails.application.routes.recognize_path('host/admin/appliance_types')
```
is throwing
```
ActionController::RoutingError: No route matches "http://localhost:3000/admin/appliance_types/4
```
The fix is to use `Atmosphere::Engine` instead of `Rails` and change `admin/appliance_types` into `atmosphere/admin/appliance_types`.
Fix #91
=> Fix removing VMT from AT using admin view

app/models/atmosphere/virtual_machine.rb, spec/models/atmosphere/virtual_machine_spec.rb
We can ignore it since reboot is already in progress.
Fix #100
=> Ignore second reboot conflict exception

app/views/atmosphere/admin/appliance_types/_view.html.haml, config/locales/en.yml
Buttons on admin AT show view, before:
after:
=> Correct delete button title on AT admin view

app/queries/atmosphere/appliances_affected_by_pmt.rb, spec/queries/atmosphere/appliances_affected_by_pmt_spec.rb
When `PortMappingTemplate` is added, removed from `ApplianceType` only `Appliances` started in production should be affected. Development `Appliances` have PMT copied into `DevModePropertySet` and should not be modified.
Fix #135
/cc @dice-cyfronet/atmo-dev-team please take a look. If you have better way how to select only production appliances please let me know.
=> Don't select development appliances on AT PMT change

README.md, lib/atmosphere/engine.rb, lib/generators/atmosphere/install_generator.rb
See http://pivotallabs.com/leave-your-migrations-in-your-rails-engines for details.
For vph, plgrid and exp dedicated sql script which removes copied atmo migrations numbers from schema table and add origin numbers need to be created and performed before pushing this change.
This change requires dependent projects to remove old migration timestamps from DB and add original atmosphere migration timestamps. 
Below is the status of dependent projects preparation for this change:
=> Use Atmosphere engine migrations in project using Atmosphere

app/models/atmosphere/user_fund.rb, spec/models/atmosphere/user_fund_spec.rb
Fixes #155 
The reallocate_default callback was called improperly often. I fixed that with Proc condition. While I'm not able to prove this will fix the issue (it's an issue that is quite difficult to recreate), I believe this was the cause.
=> reallocate_default callback condition fixed

spec/lib/atmosphere_spec.rb
Fix:
```
/home/travis/build/dice-cyfronet/atmosphere/spec/lib/atmosphere_spec.rb:96: warning: already initialized constant PROVIDER_CONF_STR
/home/travis/build/dice-cyfronet/atmosphere/spec/lib/atmosphere_spec.rb:88: warning: previous definition of PROVIDER_CONF_STR was here
/home/travis/build/dice-cyfronet/atmosphere/spec/lib/atmosphere_spec.rb:97: warning: already initialized constant PROVIDER_CONF
/home/travis/build/dice-cyfronet/atmosphere/spec/lib/atmosphere_spec.rb:89: warning: previous definition of PROVIDER_CONF was here
./home/travis/build/dice-cyfronet/atmosphere/spec/lib/atmosphere_spec.rb:104: warning: already initialized constant PROVIDER_CONF_STR
/home/travis/build/dice-cyfronet/atmosphere/spec/lib/atmosphere_spec.rb:96: warning: previous definition of PROVIDER_CONF_STR was …
```
=> Clean nic provider spec

app/models/atmosphere/billing_log.rb
Month were wrongly displayed. Also, due to UTC/CET dates querying problem last year's May could, in some cases, replace data for this year's month.
=> ordering_and_13_months_fix

app/models/atmosphere/virtual_machine_flavor.rb, spec/models/atmosphere/virtual_machine_flavor_spec.rb
Fixes #182 
Also prevents VMF.destroy if there are VMs attached to that flavor.
=> VMF model equipped with two new callbacks

app/services/atmosphere/vm_updater.rb, spec/services/atmosphere/vm_updater_spec.rb
This is a fix for: https://redmine.dev.cyfronet.pl/issues/3329. It solves following problem:
* VM is in state active
* Save button is clicked as a result new template should be created and state is changed into saving
* We are canceling appliance saving process after e.g. 10s - open stack correctly removes template connected with deleted AT
* As a result state of the appliance changes from "saving" into "active" right now. In the nova VM state is set to "active" but "task_state" is set to "image_pending_upload" - openstack does not cancel this operation for some reason. 
* Now if we will try to save appliance once again Atmosphere throws error.
=> VM in saving state when task state is image_pending_upload

app/controllers/atmosphere/admin/appliance_sets_controller.rb, app/controllers/atmosphere/api/v1/appliance_sets_controller.rb, app/controllers/atmosphere/api/v1/appliances_controller.rb, app/models/atmosphere/appliance.rb, app/models/atmosphere/appliance_set.rb, app/services/atmosphere/destroy_appliance.rb, app/services/atmosphere/destroy_appliance_set.rb, app/services/atmosphere/optimizer.rb, config/locales/en.yml, spec/models/atmosphere/appliance_set_spec.rb, spec/models/atmosphere/appliance_spec.rb, spec/requests/atmosphere/api/appliances_spec.rb, spec/services/atmosphere/billing_service_spec.rb, spec/services/atmosphere/destroy_appliance_set_spec.rb, spec/services/atmosphere/destroy_appliance_spec.rb, spec/services/atmosphere/optimizer_spec.rb
Code for scaling and destroying unused VM was removed from optimizer and appliance callbacks and moved into dedicated services.
=> Use optimizer services

app/views/layouts/atmosphere/_navbar.html.haml, app/views/layouts/atmosphere/application.html.haml
GWT is not compatible with turbolinks, that is why it need to be turned off for `home#index` view.
=> Turn off turbolinks for clew views

Gemfile, Gemfile.lock, README.md
We need `ffaker` in version at least 2.0.0. This dependency need to be installed in dependent project to use atmosphere factories.
/cc @dice-cyfronet/atmo-dev-team please take a look.
Fixes #153
=> Mention about using factories in dependent projects

app/abilities/atmosphere/tenant_ability_builder.rb, spec/requests/atmosphere/api/compute_sites_spec.rb
Adds a restriction in Tenant ability builder to ensure that users can only read tenants which they share a fund with.
=> Scope tenants for current user

app/controllers/atmosphere/admin/funds_controller.rb, app/models/atmosphere/fund.rb, app/views/atmosphere/admin/funds/_form.html.haml
Fund name is used in plgrid to distinguish default team fund. That is why there should not be possible to edit fund name. I believe that is does not have any drawbacks in other projects.
=> Don't allow to modify fund name after it is created

app/models/atmosphere/http_mapping.rb, spec/factories/tenants.rb, spec/services/atmosphere/proxy/appliance_proxy_updater_spec.rb
Site is can be shared among many tenants. It is used distinguish correct Redis queue name to generate add/remove http/https proxies jobs.
=> Use tenant `site_id` to generate redirus tasks

app/services/atmosphere/flavor_manager.rb, app/services/atmosphere/flavor_updater.rb, app/services/atmosphere/flavor_updater_ext.rb, app/workers/atmosphere/flavor_worker.rb, config/locales/en.yml, lib/atmosphere/clockwork.rb, spec/services/atmosphere/flavor_manager_spec.rb, spec/services/atmosphere/flavor_updater_spec.rb
Flavor cost can be calculated by extended project by implementing `Atmosphere::FlavorUpdaterExt#calculate_price(flavor)` method. To allow such a case following actions were needed (and are implemented in this PR):
- static methods were removed
- `Atmosphere::FlavorUpdaterExt` were added
=> Flavor prices

app/controllers/atmosphere/api/v1/appliance_types_controller.rb, app/controllers/atmosphere/api/v1/appliances_controller.rb, app/controllers/atmosphere/api/v1/clew_controller.rb, app/controllers/atmosphere/api/v1/virtual_machine_templates_controller.rb, app/models/atmosphere/user.rb, app/providers/atmosphere/optimization_strategy/default.rb, app/serializers/atmosphere/appliance_type_serializer.rb, app/serializers/atmosphere/clew_appliance_types_serializer.rb, app/serializers/atmosphere/virtual_machine_template_serializer.rb, spec/requests/atmosphere/api/appliance_types_spec.rb, spec/requests/atmosphere/api/appliances_spec.rb, spec/requests/atmosphere/api/clew_spec.rb, spec/requests/atmosphere/api/virtual_machine_templates_spec.rb, spec/serializers/atmosphere/appliance_type_serializer_spec.rb, spec/serializers/atmosphere/clew_appliance_instances_serializer_spec.rb, spec/support/matchers.rb
Restricts visibility of VMTs and Tenants in controllers to those which the current user is authorized to access (through Funds). Added a loophole for admins to enable them to see all VMTs.
=> Scope vmts by user funds

app/controllers/atmosphere/api/v1/appliance_sets_controller.rb, app/controllers/atmosphere/api/v1/appliances_controller.rb, app/models/atmosphere/appliance.rb, app/services/atmosphere/create_appliance_service.rb, spec/models/atmosphere/action_spec.rb, spec/models/atmosphere/appliance_spec.rb, spec/requests/atmosphere/api/actions_spec.rb, spec/requests/atmosphere/api/appliance_sets_spec.rb, spec/requests/atmosphere/api/appliances_spec.rb, spec/services/atmosphere/cloud/satisfy_appliance_spec.rb, spec/services/atmosphere/cloud/scale_appliance_spec.rb, spec/services/atmosphere/optimizer_spec.rb
This is a first step to make optimization asynchronous. Optimization execution was removed from appliance callback and moved into dedicated service.
=> Move optimize appliance into service from callback

.travis.yml
Travis introduced container infrastructure. It is faster and more resources are available there. What is more builds can be even faster by caching bundler gem fetch.
=> Travis builds use container infrastructure + bundle cache

app/models/atmosphere/tenant.rb, lib/support/redirus/http.conf.erb, lib/support/redirus/https.conf.erb, spec/models/atmosphere/tenant_spec.rb
This change guarantees backward compatibility. `site_id` is used to get
correct queue name while generating job to add/remove http/https
redirection. Previously `tenant_id` was used for it. This change
guarantee backward compatibility and allow to override queue using
`site_id` field.
Fix #237 
@dice-cyfronet/atmo-dev-team please take a look.
=> Use tenant_id when site_id is nil

.rubocop.yml, Gemfile, Gemfile.lock, app/controllers/atmosphere/api/v1/appliance_sets_controller.rb, config/locales/en.yml, spec/requests/atmosphere/api/appliance_sets_spec.rb
https://github.com/dice-cyfronet/atmosphere/issues/221
Non-admin users were not allowed by abilities to create appl set with arbitrary type,
however admin user could do it. If admin provided an invalid type a 500 error occured
due to invoking a method on a nil object.
Since this commit it is checked if appliance set type is properly set
and an appropriate error message and 422 status code are returned in response.
Fix #221.
=> Validate that admin provided valid AS type

Gemfile.lock, config/initializers/unify_openstack.rb
This PR restores old fog implementation, where were possible to remove server and image using `servers` and `images` model.
=> Fix delete vm vmt

spec/requests/atmosphere/api/clew_spec.rb
=> Verify that clew correctly hides appliance types which have VMTs only on inactive tenants

app/providers/atmosphere/optimization_strategy/manual.rb, spec/providers/atmosphere/optimization_strategy/manual_spec.rb
https://github.com/dice-cyfronet/atmosphere/issues/75
If used to fail if optimization_strategy_params or optimization_strategy_params['vms']
were nil.
=> checking for nil values in new_v__a_f_a_t method

doc/api/README.md
https://github.com/dice-cyfronet/atmosphere/issues/249
There used to be a valid domain name in examples so user could by accident send her/his private token to a public web server.
=> removed exisitng DNS from API examples

app/controllers/atmosphere/api/v1/endpoints_controller.rb, app/controllers/atmosphere/api/v1/port_mapping_properties_controller.rb, app/controllers/atmosphere/api/v1/port_mapping_templates_controller.rb, doc/api/endpoints.md, doc/api/port_mapping_properties.md, doc/api/port_mapping_templates.md, spec/requests/atmosphere/api/endpoints_spec.rb, spec/requests/atmosphere/api/port_mapping_properties_spec.rb, spec/requests/atmosphere/api/port_mapping_templates_spec.rb
User will not be able to change assignment between
* `port mapping template` and `appliance type` or `dev mode property set`
* `port mapping property` and `port mapping template`
* `endpoint` and `port mapping template`
during update (`PUT`) operation. This MR fixes 2 first issues discovered by security audit.
=> Don't allow to change PMT, PMP, endpoint assignment on update

app/models/atmosphere/user_key.rb
https://github.com/dice-cyfronet/atmosphere/issues/256
If filename of the public key was manipulated running ssh-keygen command could be exploited
to inject some code to shell. Current invocation of ssh-keygen is safer.
Fix #256.
=> enhanced fingerprint generation

app/controllers/atmosphere/api/v1/virtual_machine_flavors_controller.rb, app/providers/atmosphere/optimization_strategy/default.rb, spec/services/atmosphere/optimizer_spec.rb
Completely eliminates the n+1 query problem in optimizer.select_tmpl_and_flavor_and_tenant, thus fixing a nasty performance bug in PL-Grid Atmosphere deployment.
=> Optimize tenant, flavor and template selection

Gemfile.lock, app/models/atmosphere/user_key.rb, atmosphere.gemspec, lib/atmosphere/engine.rb, spec/models/atmosphere/user_key_spec.rb, spec/requests/atmosphere/api/user_keys_spec.rb
Previously system command was used. This was OS specific and e.g. on Ubuntu 15.10 this does not work. Now `sshkey` library is used which should be agnostic.
=> Use sshkey lib to generate public key fingerprint

app/workers/atmosphere/cloud/vm_destroy_worker.rb, spec/workers/atmosphere/cloud/vm_destroy_worker_spec.rb
Fixes problem with failing jobs, when trying to delete not existing VMs
=> Remove VM only when it exists, do nothing otherwise

app/workers/atmosphere/endpoint_status_check_worker.rb, lib/atmosphere.rb, spec/workers/atmosphere/endpoint_status_check_worker_spec.rb
Url checker timeout can be configured using:
```ruby
Atmosphere.setup do |config|
config.url_monitoring.timeout = 123
end
```
@nowakowski, @tbartynski  please take a look
=> Possibility to configure url checker, timeout set to 1s
